name: Daily Duaa

on:
  schedule:
    - cron: '0 20 * * *'  # Every day at 8 PM UTC
  workflow_dispatch:

jobs:
  post-duaa:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Restore last index cache
        id: cache
        uses: actions/cache@v4
        with:
          path: last_index.txt
          key: dua-index-cache
          restore-keys: dua-index-cache

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Run script
        env:
          API_KEY: ${{ secrets.API_KEY }}
          API_SECRET: ${{ secrets.API_SECRET }}
          ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
          ACCESS_TOKEN_SECRET: ${{ secrets.ACCESS_TOKEN_SECRET }}
        run: python post_duaa.py

      - name: Save updated last index
        if: always()
        uses: actions/cache@v4
        with:
          path: last_index.txt
          key: dua-index-cache
          restore-keys: dua-index-cache